---
name: Continuous Integration

on:
  push:
    branches: [develop, modern-cmake]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GTEST_COLOR: 1
jobs:
  host_build_test:
    name: Host Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake --preset Build-Test
          cmake --build Build-Test
          ctest --test-dir Build-Test --quiet --no-compress-output --output-on-failure
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ["5-2016-q3", "6-2017-q2", "7-2018-q2", "8-2019-q3"]
    steps:
      - uses: actions/checkout@v2
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.gcc }}
      - run: |
          cmake --preset Build-Host -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build Build-Host
          cmake --preset Build-Embedded -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build Build-Embedded
