name: build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake -E make_directory Build && cd Build
          cmake .. -DCCOLA_DIR=ccola -DCCOLA_INSTALL_DIR=Install -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
          ctest -C Debug -T Test --output-on-failure
