---
name: Continuous Integration

on:
  push:
    branches: [develop, modern-cmake]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  GTEST_COLOR: 1
jobs:
  host_build_test:
    name: Host Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test
        run: |
          cmake -B Build -DCMAKE_BUILD_TYPE=Debug
          cmake --build Build --config Debug
          pushd Build && ctest -Q -C Debug -T Test --no-compress-output --output-on-failure
  embedded_build:
    name: Embedded Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc: ["5-2016-q3", "6-2017-q2", "7-2018-q2", "8-2019-q3"]
    steps:
      - uses: actions/checkout@v2
      - name: Install GNU Arm Embedded Toolchain ${{ matrix.gcc }}
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: ${{ matrix.gcc }}
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.gcc }}
      - run: |
          cmake -B Build-Host -G Ninja -DCMAKE_BUILD_TYPE=Release -DEMIL_BUILD_TESTS=Off -DEMIL_BUILD_EXAMPLES=Off -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build Build-Host --config Release
          cmake -B Build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Build-Host -DCMAKE_TOOLCHAIN_FILE=cmake/toolchain-arm-gcc.cmake -DEMIL_PACKAGE_CONFIG_IMPORT_NAMESPACE="emil::"
          cmake --build Build --config Release
